package view;
import view.DangKyKhamView;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import model.BenhAn;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;
public class BenhAnView extends javax.swing.JFrame {

    /** 
     * Creates new form BenhAnView
     */
    List <BenhAn> list = new ArrayList<BenhAn>();
    BenhAn y;
    private static int c = 0;
    private static int kt = 0;
    public BenhAnView() {
        initComponents();
        setLocationRelativeTo(null);
        try {
            SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
            Date ngaySinh = formatter.parse("20-10-2005");
            list.add(new BenhAn(7687, "tuan", "ausf", "asjhgd", "asiyf", "ashgf", ngaySinh));
        } catch (ParseException e) {
            e.printStackTrace();
        }

        
        ViewBA();
        ViewTableBA();
    }
    public void addBenhAn(BenhAn benhAn) {
        list.add(benhAn);
        ViewTableBA(); // Cập nhật bảng hiển thị
    }
    public void ViewBA(){
        y = list.get(c);
        this.txtId.setText("" + y.getID());
        this.txtTrieuChung.setText(y.getTrieuChung());
        this.txtChuanDoan.setText(y.getChanDoan());
        this.txtChiDinh.setText(y.getChiDinh());
        this.txtKetLuan.setText(y.getKetLuan());
        this.txtDonThuoc.setText(y.getDonThuoc());
        this.txtDate.setDate(y.getNgayKham());
        
        OnOff(true, false);
    }
    public void ViewTableBA(){
        DefaultTableModel model = (DefaultTableModel) this.tblBenhAn2.getModel();
        model.setNumRows(0);
        int n = 1;
        for(BenhAn y : list){
            model.addRow(new Object[]{n++,y.getID(), y.getTrieuChung(), y.getChanDoan(), y.getChiDinh(), y.getKetLuan(), y.getDonThuoc(), y.getNgayKham()});
        }
        this.tblBenhAn2.setRowHeight(20);
    }
    public void OnOff(boolean a, boolean b){
        this.btnSaveBA.show(b);
        this.btnCancelBA.show(b);
        this.btnAddBA.show(a);
        this.btnEditBA.show(a);
        this.btnDeleteBA.show(a);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTrieuChung = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtChuanDoan = new javax.swing.JTextField();
        txtChiDinh = new javax.swing.JTextField();
        txtKetLuan = new javax.swing.JTextField();
        txtDonThuoc = new javax.swing.JTextField();
        btnAddBA = new javax.swing.JButton();
        btnDeleteBA = new javax.swing.JButton();
        btnEditBA = new javax.swing.JButton();
        btnSaveBA = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnCancelBA = new javax.swing.JButton();
        txtDate = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBenhAn2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("ID Bệnh nhân:");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Chuẩn đoán:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Triệu chứng:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Đơn thuốc:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Chỉ định:");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Kết luận:");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Ngày khám:");

        txtTrieuChung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTrieuChungActionPerformed(evt);
            }
        });

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        txtChuanDoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChuanDoanActionPerformed(evt);
            }
        });

        txtChiDinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChiDinhActionPerformed(evt);
            }
        });

        txtKetLuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKetLuanActionPerformed(evt);
            }
        });

        txtDonThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDonThuocActionPerformed(evt);
            }
        });

        btnAddBA.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnAddBA.setText("Thêm");
        btnAddBA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBAActionPerformed(evt);
            }
        });

        btnDeleteBA.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnDeleteBA.setText("Xóa");
        btnDeleteBA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteBAActionPerformed(evt);
            }
        });

        btnEditBA.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnEditBA.setText("Sửa");
        btnEditBA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditBAActionPerformed(evt);
            }
        });

        btnSaveBA.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnSaveBA.setText("Lưu");
        btnSaveBA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveBAActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnBack.setText("Quay lại");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnCancelBA.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCancelBA.setText("Hủy bỏ");
        btnCancelBA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelBAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddBA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBack)
                            .addComponent(btnDeleteBA))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addComponent(btnEditBA)
                        .addGap(955, 955, 955))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtDonThuoc, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                .addComponent(txtKetLuan)
                                .addComponent(txtChiDinh)
                                .addComponent(txtChuanDoan)
                                .addComponent(txtTrieuChung)
                                .addComponent(txtId))
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(btnSaveBA)
                .addGap(100, 100, 100)
                .addComponent(btnCancelBA)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTrieuChung, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtChuanDoan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtChiDinh, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKetLuan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDonThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddBA)
                    .addComponent(btnDeleteBA)
                    .addComponent(btnEditBA))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveBA)
                    .addComponent(btnCancelBA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(29, 29, 29))
        );

        tblBenhAn2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "ID", "Triệu chứng", "Chuẩn Đoán", "Chỉ định", "Kết luận", "Đơn thuốc", "Ngaykham"
            }
        ));
        tblBenhAn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBenhAn2MouseClicked(evt);
            }
        });
        tblBenhAn2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblBenhAn2KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tblBenhAn2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddBAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBAActionPerformed
        // TODO add your handling code here:
        this.txtId.setText("");
        this.txtTrieuChung.setText("");
        this.txtChuanDoan.setText("");
        this.txtChiDinh.setText("");
        this.txtKetLuan.setText("");
        this.txtDonThuoc.setText("");
        this.txtDate.setDate(new Date());
        kt = 1;
        
        OnOff(false, true);
    }//GEN-LAST:event_btnAddBAActionPerformed

    private void btnEditBAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditBAActionPerformed
        // TODO add your handling code here:
        OnOff(false, true);
        kt = -1;
    }//GEN-LAST:event_btnEditBAActionPerformed

    private void btnDeleteBAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBAActionPerformed
        // TODO add your handling code here:
        list.remove(c);
        ViewBA();
        ViewTableBA();
    }//GEN-LAST:event_btnDeleteBAActionPerformed

    private void btnCancelBAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelBAActionPerformed
        // TODO add your handling code here:
        ViewBA();
    }//GEN-LAST:event_btnCancelBAActionPerformed

    private void btnSaveBAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveBAActionPerformed
        // TODO add your handling code here:
        int ID = Integer.parseInt(this.txtId.getText()) ;
        String TrieuChung = this.txtTrieuChung.getText();
        String ChuanDoan = this.txtChuanDoan.getText();
        String ChiDinh = this.txtChiDinh.getText();
        String KetLuan = this.txtKetLuan.getText();
        String DonThuoc = this.txtKetLuan.getText();
        Date NgayKham = this.txtDate.getDate();
        
        
        if(kt == 1){
            list.add(new BenhAn(ID,TrieuChung,ChuanDoan,ChiDinh,KetLuan,DonThuoc,NgayKham));
        }
        if(kt == -1){
            list.set(c,new BenhAn(ID,TrieuChung,ChuanDoan,ChiDinh,KetLuan,DonThuoc,NgayKham));
        }
        ViewBA();
        ViewTableBA();
    }//GEN-LAST:event_btnSaveBAActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtTrieuChungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTrieuChungActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTrieuChungActionPerformed

    private void txtChuanDoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChuanDoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChuanDoanActionPerformed

    private void txtChiDinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChiDinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChiDinhActionPerformed

    private void txtKetLuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKetLuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKetLuanActionPerformed

    private void txtDonThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDonThuocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDonThuocActionPerformed

    private void tblBenhAn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBenhAn2MouseClicked
        // TODO add your handling code here:
        c = this.tblBenhAn2.getSelectedRow();
        ViewBA();
    }//GEN-LAST:event_tblBenhAn2MouseClicked

    private void tblBenhAn2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblBenhAn2KeyReleased
        // TODO add your handling code here:
        c = this.tblBenhAn2.getSelectedRow();
        ViewBA();
    }//GEN-LAST:event_tblBenhAn2KeyReleased

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        DangKyKhamView dangKyKhamView = new DangKyKhamView();
        dangKyKhamView.setVisible(true); // Hiển thị giao diện DangKyKhamView
        this.dispose(); // Ẩn giao diện login
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BenhAnView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BenhAnView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BenhAnView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BenhAnView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BenhAnView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBA;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCancelBA;
    private javax.swing.JButton btnDeleteBA;
    private javax.swing.JButton btnEditBA;
    private javax.swing.JButton btnSaveBA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblBenhAn2;
    private javax.swing.JTextField txtChiDinh;
    private javax.swing.JTextField txtChuanDoan;
    private com.toedter.calendar.JDateChooser txtDate;
    private javax.swing.JTextField txtDonThuoc;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtKetLuan;
    private javax.swing.JTextField txtTrieuChung;
    // End of variables declaration//GEN-END:variables
}
